"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const multer_1 = __importDefault(require("multer"));
const OrphanageController_1 = __importDefault(require("./app/controllers/OrphanageController"));
const UserController_1 = __importDefault(require("./app/controllers/UserController"));
const SessionController_1 = __importDefault(require("./app/controllers/SessionController"));
const PendingOrphanagesController_1 = __importDefault(require("./app/controllers/PendingOrphanagesController"));
const FileController_1 = __importDefault(require("./app/controllers/FileController"));
const ResetPasswordController_1 = __importDefault(require("./app/controllers/ResetPasswordController"));
const NotifiactionController_1 = __importDefault(require("./app/controllers/NotifiactionController"));
const upload_1 = __importDefault(require("./config/upload"));
const auth_1 = __importDefault(require("./app/middlewares/auth"));
const isAdmin_1 = __importDefault(require("./app/middlewares/isAdmin"));
const routes = express_1.Router();
const upload = multer_1.default(upload_1.default);
routes.post('/users', UserController_1.default.create);
routes.post('/session', SessionController_1.default.create);
routes.post('/password/forgot', ResetPasswordController_1.default.create);
routes.put('/password/reset/:token', ResetPasswordController_1.default.update);
// Operations that only authenticated users can do;
routes.use(auth_1.default);
routes.get('/orphanages', OrphanageController_1.default.index);
routes.get('/orphanages/:orphanage_id', OrphanageController_1.default.show);
routes.post('/orphanages', upload.array('images'), OrphanageController_1.default.create);
routes.get('/notifications', NotifiactionController_1.default.index);
routes.put('/notifications/:notification_id', NotifiactionController_1.default.update);
// Operations that only administrators can do;
routes.use(isAdmin_1.default);
routes.get('/pending', PendingOrphanagesController_1.default.index);
routes.put('/orphanages/accept/:orphanage_id', PendingOrphanagesController_1.default.update);
routes.delete('/orphanages/refuse/:orphanage_id', PendingOrphanagesController_1.default.destroy);
routes.put('/orphanages/:orphanage_id', upload.array('images'), OrphanageController_1.default.update);
routes.delete('/orphanages/:orphanage_id', OrphanageController_1.default.destroy);
routes.delete('/orphanages/images/:image_id', FileController_1.default.destroy);
exports.default = routes;
//# sourceMappingURL=routes.js.map